/* Five map/visit controls. Numerical maps and geometry have separate gates. */
(()=>{'use strict';
const $=id=>document.getElementById(id),T=window.ReportTexture,C=window.CornealData,V=window.VisitComparison,N=window.NumericalMaps;
let context={session:null,slots:[]},sets=[],visit='first',role='curvature_front',lastHeight=0;
const pageCache=new Map(),bundleCache=new Map(),state=Object.fromEntries(['OD','OS'].map(eye=>[eye,{generation:0,data:null,model:null,source:null,region:null}]));
const eyes=Object.fromEntries(['OD','OS'].map(eye=>[eye,new NumericalEye3D.NumericalEye($(eye+'-eye'),$(eye+'-fallback'))]));
const visitLabel=()=>visit==='first'?'Baseline':visit==='latest'?'Latest':'Change',label=()=>T.LABELS[role];
function post(type,extra={}){window.parent.postMessage({type:'nkpi:cornea:'+type,...extra},location.origin);}
function height(){const h=Math.ceil($('atlas').getBoundingClientRect().height)+6;if(h!==lastHeight){lastHeight=h;post('height',{height:h});}}
new ResizeObserver(()=>requestAnimationFrame(height)).observe($('atlas'));
function sanitizeMaps(raw){if(!Array.isArray(raw)||raw.length>4)throw Error('Invalid map slots.');const seen=new Set();return raw.map(s=>{const key=s.eye+':'+s.visit;if(!['OD','OS'].includes(s.eye)||!['first','latest'].includes(s.visit)||seen.has(key)||!s.source_id||!Array.isArray(s.pages)||s.pages.length>48)throw Error('Invalid source association.');seen.add(key);const ids=new Set(),pages=s.pages.map(p=>{if(!T.localBlob(p.url)||typeof p.id!=='string'||ids.has(p.id)||!/^[a-z0-9-]{1,60}$/i.test(p.id))throw Error('Invalid source page.');ids.add(p.id);return {id:p.id,url:p.url,kind:['topometric','belin','progression','report'].includes(p.kind)?p.kind:'report',label:String(p.label||'Report').slice(0,140),map_regions:T.sanitizeHints(p.map_regions)};});let surface=null;if(s.surface){surface=C.validate(s.surface);if(surface.eye!==s.eye||surface.visit!==s.visit)throw Error('Numerical map eye or visit mismatch.');}return {eye:s.eye,visit:s.visit,source_id:String(s.source_id).slice(0,100),pages,surface};});}
const setFor=(eye,v)=>sets.find(s=>s.eye===eye&&s.visit===v),confirmed=(eye,v)=>context.slots.some(s=>s.eye===eye&&s.visit===v&&s.source_confirmed===true);
const shownEyes=()=>context.session!==null?[...new Set(context.slots.map(s=>s.eye))]:['OD'];
function status(eye,text,mode='ready'){$(eye+'-status').textContent=text;$(eye+'-status').dataset.state=mode;height();}
function clearEye(eye){const s=state[eye];s.generation++;s.data=null;s.model=null;s.source=null;s.region=null;eyes[eye].setModel(null);eyes[eye].setTexture(null);$(eye+'-legend').hidden=true;$(eye+'-readout').textContent='';$(eye+'-flat').getContext('2d').clearRect(0,0,480,480);$(eye+'-flat-wrap').hidden=true;}
function reset(){sets=[];pageCache.clear();bundleCache.clear();visit='first';role='curvature_front';for(const e of ['OD','OS']){clearEye(e);eyes[e].clear();}render();}
async function readPage(page){if(!pageCache.has(page.url))pageCache.set(page.url,T.load(page.url));const loaded=await pageCache.get(page.url);return {...loaded,regions:T.withHints(T.describe(loaded,page.kind),page.map_regions)};}
async function resolveReport(current,requested){if(!current)return null;const preferred=requested==='curvature_front'?'topometric':'belin';const pages=[...current.pages].filter(p=>p.kind!=='progression').sort((a,b)=>Number(b.kind===preferred)-Number(a.kind===preferred));for(const page of pages)try{const loaded=await readPage(page),region=T.roleRegion(loaded.regions,requested);if(region)return {page,loaded,region};}catch(_){}return null;}
async function bundle(current){const key=current.eye+':'+current.visit+':'+current.source_id;if(bundleCache.has(key))return bundleCache.get(key);const job=(async()=>{const maps={},errors={},reports={};await Promise.all(['curvature_front','thickness'].map(async requested=>{try{if(current.surface){maps[requested]=N.nativeMap(current.surface,requested);return;}const report=await resolveReport(current,requested);if(!report)throw Error(T.LABELS[requested]+' could not be identified in this report.');reports[requested]=report;maps[requested]=await N.extract(report);}catch(error){errors[requested]=error.message;}}));let model=null;try{model=N.measuredModel(current.surface)||N.reconstruct(maps.curvature_front,maps.thickness);}catch(_){}return {maps,errors,reports,model};})();bundleCache.set(key,job);return job;}
function drawFlat(eye,texture){const c=$(eye+'-flat'),ctx=c.getContext('2d');c.width=c.height=480;ctx.fillStyle='#171525';ctx.fillRect(0,0,480,480);ctx.save();ctx.beginPath();ctx.arc(240,240,239,0,Math.PI*2);ctx.clip();ctx.fillStyle='#454451';ctx.fillRect(0,0,480,480);ctx.strokeStyle='#5f5d6a';ctx.lineWidth=1;for(let d=-480;d<960;d+=13){ctx.beginPath();ctx.moveTo(d,0);ctx.lineTo(d+480,480);ctx.stroke();}ctx.drawImage(texture,0,0,480,480);ctx.restore();$(eye+'-flat-wrap').hidden=false;}
function legend(eye,d){$(eye+'-legend').hidden=false;let lo,hi,colors=[];if(d.isChange){lo=-d.limit;hi=d.limit;for(let i=0;i<=20;i++)colors.push('rgb('+N.deltaColor(lo+(hi-lo)*i/20,d.limit).join(',')+') '+i*5+'%');$(eye+'-mid').textContent='0';}else{lo=d.role==='thickness'?300:10;hi=d.role==='thickness'?900:90;for(let i=0;i<=80;i++)colors.push('rgb('+N.sourceColor(d,lo+(hi-lo)*i/80).join(',')+') '+i*1.25+'%');$(eye+'-mid').textContent=N.format((lo+hi)/2,d.dp);}$(eye+'-spectrum').style.background='linear-gradient(90deg,'+colors.join(',')+')';$(eye+'-low').textContent=N.format(lo,d.dp,d.isChange)+' '+d.unit;$(eye+'-high').textContent=N.format(hi,d.dp,d.isChange)+' '+d.unit;$(eye+'-axis').textContent=d.isChange?(d.role==='thickness'?'Negative = thinner · positive = thicker.':'Positive = steeper · negative = flatter.'):'Original absolute color palette · '+(d.role==='thickness'?'thickness in µm.':'radius converted to keratometric dioptres.');}
function paint(eye){const s=state[eye],d=s.data;if(!d)return;const texture=N.texture(d);drawFlat(eye,texture);eyes[eye].setTexture(N.originalTexture(d)||texture);eyes[eye].textureRadius=Math.max(...d.x.map(Math.abs),...d.y.map(Math.abs));legend(eye,d);}
function finish(eye,d,model){const s=state[eye];s.data=d;s.model=model;eyes[eye].setModel(model,d.role==='thickness'&&!!(model?.posterior||model?.kind==='estimated'));if(d.isChange){const active=shownEyes().filter(e=>state[e].data?.isChange),limit=Math.max(...active.map(e=>state[e].data.limit));for(const e of active){state[e].data.limit=limit;paint(e);}}else paint(eye);const estimated=d.kind==='estimated',synthetic=d.kind==='synthetic';$(eye+'-stamp').textContent=(model?model.kind==='estimated'?'APPROXIMATE RECONSTRUCTION':model.kind==='synthetic'?'SYNTHETIC SURFACE':'SUPPLIED SURFACE':'REFERENCE SHAPE')+(d.isChange?' · LATEST GEOMETRY':d.kind==='estimated'?(d.role==='curvature_front'?' · SOURCE RADIUS mm':' · SOURCE µm'):'');$(eye+'-flat-label').textContent=(synthetic?'Synthetic ':estimated?'Estimated ':'Numerical ')+(d.isChange?'latest − baseline':visitLabel().toLowerCase())+' · '+d.unit;const text=estimated?(d.isChange?'Estimated report-coordinate difference. Small changes can reflect color quantization or scan alignment.':'Values estimated from the printed color scale; original absolute map colors are reproduced.'):'Values from the validated numerical export'+(d.isChange?' at its declared registered coordinates.':'.');status(eye,text+' Hatched areas are unavailable. '+(model?.kind==='estimated'?'3D shape uses smoothed curvature; thickness is a modeled depth offset.':model?'3D cap uses supplied coordinates.':'Measured surface coordinates are unavailable.'));$(eye+'-readout').textContent='Select a point on the heatmap for values.';}
async function show(eye){const s=state[eye],generation=s.generation,requested=role,selectedVisit=visit;const stale=()=>generation!==s.generation;try{
 if(selectedVisit==='change'){const a=setFor(eye,'first'),b=setFor(eye,'latest');if(!a||!b)throw Error('Import baseline and latest visits for this eye to calculate Change.');if(!confirmed(eye,'first')||!confirmed(eye,'latest'))throw Error('Verify both visit sources in step 3 to calculate Change.');if(a.source_id===b.source_id)throw Error('Change requires two distinct visit sources.');if(!!a.surface!==!!b.surface)throw Error('Both visits must use the same numerical source: device exports or calibrated report images.');status(eye,'Calculating numerical '+label().toLowerCase()+' change…','loading');$(eye+'-stamp').textContent='CALCULATING CHANGE';const [ab,bb]=await Promise.all([bundle(a),bundle(b)]);if(stale())return;if(!ab.maps[requested]||!bb.maps[requested])throw Error(ab.errors[requested]||bb.errors[requested]||'Matching numerical maps are unavailable.');if(a.surface&&b.surface)V.compare(a.surface,b.surface,requested);const d=N.compare(ab.maps[requested],bb.maps[requested]);s.source=a.source_id+' / '+b.source_id;finish(eye,d,bb.model);return;}
 const current=setFor(eye,selectedVisit);if(!current)throw Error(sets.length?visitLabel()+' is not available for this eye.':'Import the report above. Curvature and thickness are selected automatically.');s.source=current.source_id;status(eye,'Preparing '+label().toLowerCase()+' map and corneal shape…','loading');$(eye+'-stamp').textContent='PREPARING MAP';if(confirmed(eye,selectedVisit)){const data=await bundle(current);if(stale())return;if(data.maps[requested]){finish(eye,data.maps[requested],data.model);return;}}const report=await resolveReport(current,requested);if(stale())return;if(report){s.region=report.region;const tex=T.crop(report.loaded.image,report.region);eyes[eye].setTexture(tex);drawFlat(eye,tex);$(eye+'-flat-label').textContent='Original report image';$(eye+'-stamp').textContent='ORIGINAL REPORT · REFERENCE SHAPE';const reason=confirmed(eye,selectedVisit)?(await bundle(current)).errors[requested]:'Verify this visit source in step 3 to enable numerical maps and modeled geometry.';if(stale())return;status(eye,reason||'Original report map. Numerical values unavailable.','unavailable');return;}throw Error(label()+' could not be identified. No other map has been substituted.');
 }catch(error){if(stale())return;$(eye+'-stamp').textContent=selectedVisit==='change'?'CHANGE UNAVAILABLE':'MAP UNAVAILABLE';status(eye,error.message,'unavailable');}}
function render(){const visible=shownEyes();$('eye-stages').classList.toggle('paired',visible.length>1);for(const b of document.querySelectorAll('[data-visit]'))b.setAttribute('aria-pressed',String(b.dataset.visit===visit));for(const b of document.querySelectorAll('[data-map]'))b.setAttribute('aria-pressed',String(b.dataset.map===role));for(const eye of ['OD','OS']){clearEye(eye);$(eye+'-card').hidden=!visible.includes(eye);$(eye+'-label').textContent=visitLabel()+' · '+label();if(visible.includes(eye))show(eye);}height();}
for(const b of document.querySelectorAll('[data-visit]'))b.addEventListener('click',()=>{visit=b.dataset.visit;render();});for(const b of document.querySelectorAll('[data-map]'))b.addEventListener('click',()=>{role=b.dataset.map;render();});
for(const eye of ['OD','OS']){eyes[eye].onChange=c=>{const other=eye==='OD'?'OS':'OD';if(!$(other+'-card').hidden)eyes[other].setCamera(c);};$(eye+'-flat').addEventListener('pointerdown',e=>{const d=state[eye].data;if(!d)return;const b=$(eye+'-flat').getBoundingClientRect(),p=N.pick(d,(e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height);if(!p)return;const prefix=d.kind==='estimated'?'≈ ':'';$(eye+'-readout').textContent='x '+p.x.toFixed(1)+', y '+p.y.toFixed(1)+' mm · '+(d.isChange?'Baseline '+prefix+N.format(p.baseline,d.dp)+' · Latest '+prefix+N.format(p.latest,d.dp)+' · Change '+prefix+N.format(p.value,d.dp,true):prefix+N.format(p.value,d.dp))+' '+d.unit+(p.value===null?' · obscured / unavailable':'');});}
window.addEventListener('message',event=>{const d=event.data;if(!d||event.source!==window.parent||event.origin!==location.origin)return;if(d.type==='nkpi:cornea:init'){const changed=d.session!==context.session;context={session:d.session,slots:Array.isArray(d.slots)?d.slots.filter(s=>['OD','OS'].includes(s.eye)&&['first','latest'].includes(s.visit)):[]};if(changed)reset();else render();}else if(d.type==='nkpi:cornea:reports'&&d.session===context.session){try{sets=sanitizeMaps(d.maps);bundleCache.clear();const live=new Set(sets.flatMap(s=>s.pages.map(p=>p.url)));for(const url of pageCache.keys())if(!live.has(url))pageCache.delete(url);render();}catch(_){reset();for(const eye of shownEyes())status(eye,'Source association or numerical validation changed. Reimport the current reports.','unavailable');}}});
window.Auto3D={sanitizeMaps,debug(){return {visit,role,slots:sets.map(s=>s.eye+':'+s.visit),eyes:Object.fromEntries(['OD','OS'].map(eye=>[eye,{source:state[eye].source,region:state[eye].region,texture:!!eyes[eye].texture,changeAvailable:!!state[eye].data?.isChange,comparisonMode:state[eye].data?(state[eye].data.kind==='estimated'?'estimated':'numerical'):null,model:state[eye].model?.kind||null,count:state[eye].data?.count||0}]))};}};
render();post('ready');height();
})();
