/* Browser-only numerical viewer. Only ready and frame-height messages leave this iframe. */
(()=>{'use strict';
const $=id=>document.getElementById(id),C=window.CornealData;let context=null,data=null,accepted=false,uploadEpoch=0,lastHeight=0;
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={z_mm:'Surface height (mm)',curvature_D:'Curvature (D)',elevation_um:'Elevation residual (µm)',thickness_um:'Thickness (µm)'};
const fmt=(v,d=3)=>C.finite(v)?v.toFixed(d):'Not supplied / missing';
const renderer=new NumericalMesh.SurfaceCanvas($('mesh-canvas'),sample=>{$('sample-layer').value=sample.layer;$('sample-row').value=sample.row;$('sample-col').value=sample.col;readout();});
function post(type,details={}){window.parent.postMessage({type:'nkpi:cornea:'+type,...details},window.location.origin);}
function height(){const h=Math.ceil($('viewer').getBoundingClientRect().height)+6;if(h!==lastHeight){lastHeight=h;post('height',{height:h});}}
new ResizeObserver(()=>requestAnimationFrame(height)).observe($('viewer'));
function status(message,type=''){$('status').textContent=message;$('status').className='status '+type;}
function purge(){renderer.clear();$('controls').hidden=true;}
function clear(message){uploadEpoch++;data=null;accepted=false;$('confirm-match').checked=false;$('confirmation-row').hidden=true;$('surface-file').value='';$('data-badge').textContent='NO SURFACE DATA';$('data-badge').className='badge';purge();status(message||'Patient-specific geometry unavailable. Upload actual surface-height grids and their coordinate metadata. Report screenshots and scalar summaries cannot define a patient’s 3D cornea.');}
function slot(){const [eye,visit]=($('slot').value||'').split(':');return {eye,visit};}
function selectedLayers(){return $('layer').value==='both'?C.layers(data):[$('layer').value];}
function chooseOptions(){const layers=C.layers(data);$('layer').innerHTML=layers.map(v=>`<option value="${v}">${v[0].toUpperCase()+v.slice(1)}</option>`).join('')+(layers.length===2?'<option value="both">Anterior + posterior</option>':'');$('sample-layer').innerHTML=layers.map(v=>`<option value="${v}">${v[0].toUpperCase()+v.slice(1)}</option>`).join('');$('sample-row').max=data.y_mm.length-1;$('sample-col').max=data.x_mm.length-1;$('sample-row').value=Math.floor(data.y_mm.length/2);$('sample-col').value=Math.floor(data.x_mm.length/2);$('show-thin').checked=false;$('show-max').checked=false;renderer.resetView();mapOptions();}
function mapOptions(){const prior=$('map').value,layers=selectedLayers();$('map').innerHTML=Object.keys(names).filter(m=>layers.every(s=>C.mapGrid(data,s,m)&&C.hasCell(C.maskedHeight(data,s,m)))).map(m=>`<option value="${m}">${names[m]}</option>`).join('');if([...$('map').options].some(o=>o.value===prior))$('map').value=prior;const hasThin=Boolean(data.thickness_um),hasCurvature=layers.some(l=>data[l].curvature_D);$('show-thin').disabled=!hasThin;$('show-max').disabled=!hasCurvature;if(!hasThin)$('show-thin').checked=false;if(!hasCurvature)$('show-max').checked=false;}
function load(raw){const parsed=C.validate(raw);C.match(parsed,slot());data=parsed;accepted=parsed.kind==='synthetic';chooseOptions();if(accepted){$('data-badge').textContent='SYNTHETIC · NOT THIS PATIENT';$('data-badge').className='badge demo';$('confirmation-row').hidden=true;render();}else{$('data-badge').textContent='NUMERICAL DATA · NOT YET MATCHED';$('confirmation-row').hidden=false;status('Numerical data passed structural checks. Confirm that this export belongs to the current case, eye and visit before any patient-specific geometry is displayed.');}}
$('surface-file').addEventListener('change',async()=>{const file=$('surface-file').files[0];clear();if(!file)return;const generation=uploadEpoch;try{if(file.size>12*1024*1024)throw new Error('Surface file exceeds 12 MB. Supply a deidentified grid export with no embedded images.');const text=await file.text();if(generation!==uploadEpoch)return;load(JSON.parse(text));}catch(error){if(generation!==uploadEpoch)return;data=null;purge();status('Geometry withheld: '+error.message,'error');}});
$('confirm-match').addEventListener('change',()=>{accepted=$('confirm-match').checked;if(!accepted){purge();status('Geometry withheld until the numerical file is matched to the current case, eye and visit.');$('data-badge').textContent='NUMERICAL DATA · NOT YET MATCHED';return;}try{C.match(data,slot());$('data-badge').textContent='NUMERICAL SURFACE · OPERATOR MATCHED';render();}catch(error){accepted=false;purge();status(error.message,'error');}});
$('slot').addEventListener('change',()=>clear('Eye/visit selection changed. Reload and match the numerical export for this slot.'));
$('clear-surface').addEventListener('click',()=>clear());
function render(){if(!data||!accepted){purge();return;}try{C.match(data,slot());const layers=selectedLayers(),map=$('map').value,sample=data.kind==='synthetic',c=data.coordinate_system;$('controls').hidden=false;status(sample?'SYNTHETIC DEMONSTRATION — generated mathematical surface, not a patient, not the current calculator inputs, and not a validation of patient reconstruction.':'Measured numerical surface patch. Identity matching is operator-confirmed, not automated. Unsupported regions and missing numerical maps are not reconstructed.',sample?'demo':'');$('meta').textContent=(sample?'Synthetic file':data.eye+' · '+(data.visit==='first'?'first / only visit':'later visit'))+' | Origin: corneal vertex | +x '+c.x_positive+', +y '+c.y_positive+', +z '+c.z_positive+'. Positive x is not automatically mirrored by laterality.';
const chosen=$('sample-layer').value,markers=[];if(layers.includes(chosen)&&$('show-thin').checked&&data.thickness_um){const p=C.extrema(data,chosen,'thickness_um','min');if(p)markers.push({...p,label:'Thinnest sample',symbol:'diamond'});}if(layers.includes(chosen)&&$('show-max').checked&&data[chosen].curvature_D){const p=C.extrema(data,chosen,'curvature_D','max');if(p)markers.push({...p,label:'Maximum sampled curvature',symbol:'circle'});}
const mesh=renderer.set(data,layers,map,{markers,mapLabel:names[map]});const total=layers.length*data.x_mm.length*data.y_mm.length;$('coverage').textContent=mesh.points.length.toLocaleString()+' / '+total.toLocaleString()+' grid samples available for this overlay; '+mesh.faces.length.toLocaleString()+' supported triangles. '+data.y_mm.length+' rows × '+data.x_mm.length+' columns. No gap filling, extrapolation or vertical exaggeration.';
$('map-note').textContent=(map==='elevation_um'?layers.map(l=>{const r=data[l].elevation_reference;return l+': reported '+r.type.replaceAll('_',' ')+', fit diameter '+r.fit_diameter_mm+' mm.';}).join(' ')+' Reference geometry is not reconstructed.':map==='curvature_D'?layers.map(l=>l+': '+data[l].curvature_type.replaceAll('_',' ')+' curvature.').join(' ')+' Maximum sampled curvature is not necessarily device Kmax.':map==='thickness_um'?'Supplied device pachymetry. Thickness is not estimated from z separation, A/B radii or summary C.':'Coordinate height in the declared shared frame, not an elevation residual against a fitted sphere.')+' Face colors represent the mean of their three measured corner values; click readouts report an actual sample.'+(layers.length===2?' Transparent layers blend colors: choose one surface for quantitative inspection.':'');readout();height();}catch(error){purge();status('Geometry withheld: '+error.message,'error');}}
function readout(){if(!data||!accepted)return;const row=Number($('sample-row').value),col=Number($('sample-col').value),layer=$('sample-layer').value;if(!$('sample-row').value.trim()||!$('sample-col').value.trim()||!Number.isInteger(row)||!Number.isInteger(col)||row<0||col<0||row>=data.y_mm.length||col>=data.x_mm.length){$('readout').textContent='Choose an in-range integer row and column.';renderer.select(null);return;}const s=data[layer],pairs=[['Sample',layer+' ['+row+', '+col+']'],['x / y (mm)',fmt(data.x_mm[col])+' / '+fmt(data.y_mm[row])],['Surface z (mm)',fmt(s.z_mm[row][col],4)],['Thickness (µm)',fmt(data.thickness_um?.[row]?.[col],1)],['Curvature (D)',fmt(s.curvature_D?.[row]?.[col],2)],['Elevation residual (µm)',fmt(s.elevation_um?.[row]?.[col],2)]];$('readout').innerHTML=pairs.map(([k,v])=>'<div><small>'+escape(k)+'</small><b>'+escape(v)+'</b></div>').join('');renderer.select({row,col,layer});}
for(const id of ['sample-row','sample-col'])$(id).addEventListener('input',readout);$('sample-layer').addEventListener('change',()=>{readout();render();});$('layer').addEventListener('change',()=>{mapOptions();if($('layer').value!=='both')$('sample-layer').value=$('layer').value;render();});$('map').addEventListener('change',render);for(const id of ['show-thin','show-max'])$(id).addEventListener('change',render);
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>renderer.view(b.dataset.camera)));
document.querySelectorAll('[data-zoom]').forEach(b=>b.addEventListener('click',()=>b.dataset.zoom==='fit'?renderer.resetView():renderer.zoomBy(Number(b.dataset.zoom))));
$('demo').addEventListener('click',async()=>{clear();const generation=uploadEpoch;try{const response=await fetch('synthetic_demo.json',{cache:'no-store'});if(!response.ok)throw new Error('Synthetic fixture not found.');const raw=await response.json();if(generation===uploadEpoch)load(raw);}catch(error){if(generation===uploadEpoch)status(error.message,'error');}});
window.addEventListener('message',event=>{if(event.source!==window.parent||event.origin!==window.location.origin||event.data?.type!=='nkpi:cornea:init')return;const next=event.data;if(next.token!==context?.token){clear('Calculator inputs or case context changed. Load and match a numerical export for the current eye and visit.');context={token:next.token};const slots=Array.isArray(next.slots)?next.slots.filter(s=>['OD','OS'].includes(s.eye)&&['first','latest'].includes(s.visit)):[];$('slot').innerHTML=slots.map(s=>'<option value="'+s.eye+':'+s.visit+'">'+s.eye+' · '+(s.visit==='first'?'First / only visit':'Later visit')+'</option>').join('');}});

window.addEventListener('message',event=>{
 if(event.source!==window.parent||event.origin!==window.location.origin||event.data?.type!=='nkpi:cornea:auto')return;
 const next=event.data;clear('Numerical geometry is available only for the confirmed current source.');
 if(!next.surface||!next.slot)return;
 try{
  $('slot').innerHTML='<option value="'+escape(next.slot.eye+':'+next.slot.visit)+'">Current source</option>';
  load(next.surface);
  if(data.kind==='measured' && next.source_confirmed===true){accepted=true;$('confirm-match').checked=true;$('confirmation-row').hidden=true;$('data-badge').textContent='DECLARED NUMERICAL EXPORT · SAME ZIP';render();}
 }catch(error){data=null;purge();status('Geometry withheld: '+error.message,'error');}
});
$('slot').innerHTML='<option value="OD:first">OD · First / only visit</option>';post('ready');height();
})();
