'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../components/cornea/surface_schema.js');const demo=JSON.parse(fs.readFileSync(path.join(__dirname,'../components/cornea/synthetic_demo.json'),'utf8'));
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}const clone=()=>structuredClone(demo);
test('synthetic source visibly classified',()=>assert.equal(C.validate(demo).kind,'synthetic'));
test('summary scalars cannot become geometry',()=>assert.throws(()=>C.validate({A:6.01,B:4.17,C:330,Kmax:66.8})));
test('elevation-only residuals cannot become geometry',()=>{const d=clone();delete d.anterior.z_mm;assert.throws(()=>C.validate(d));});
test('unit mismatch blocked',()=>{const d=clone();d.units.z='um';assert.throws(()=>C.validate(d));});
test('eye mismatch blocked',()=>{const d=clone();d.kind='measured';d.source='device_numeric_export';assert.throws(()=>C.match(C.validate(d),{eye:'OS',visit:'first'}));});
test('visit mismatch blocked',()=>{const d=clone();d.kind='measured';d.source='device_numeric_export';assert.throws(()=>C.match(C.validate(d),{eye:'OD',visit:'latest'}));});
test('nonfinite blocked',()=>{const d=clone();d.anterior.z_mm[24][24]=NaN;assert.throws(()=>C.validate(d));});
test('blank-string is not zero',()=>{const d=clone();d.anterior.z_mm[24][24]='';assert.throws(()=>C.validate(d));});
test('shape mismatch blocked',()=>{const d=clone();d.anterior.z_mm.pop();assert.throws(()=>C.validate(d));});
test('unsorted axis blocked',()=>{const d=clone();d.x_mm.reverse();assert.throws(()=>C.validate(d));});
test('missing orientation blocked',()=>{const d=clone();delete d.coordinate_system;assert.throws(()=>C.validate(d));});
test('identifiers not accepted by schema',()=>{const d=clone();d.patient_name='forbidden';assert.throws(()=>C.validate(d));});
test('mask is retained without extrapolation',()=>{const d=C.validate(demo),z=C.maskedHeight(d,'anterior','z_mm');assert.equal(z[0][0],null);assert.equal(z.flat().filter(C.finite).length,d.anterior.z_mm.flat().filter(C.finite).length);});
test('overlay missingness masks its faces',()=>{const d=clone();d.anterior.curvature_D[24][24]=null;const z=C.maskedHeight(C.validate(d),'anterior','curvature_D');assert.equal(z[24][24],null);});
test('posterior is not inferred',()=>{const d=clone();delete d.posterior;assert.deepEqual(C.layers(C.validate(d)),['anterior']);});
test('thickness is not inferred',()=>{const d=clone();delete d.thickness_um;delete d.thickness_definition;assert.equal(C.mapGrid(C.validate(d),'anterior','thickness_um'),null);});
test('curvature is not inferred',()=>{const d=clone();delete d.anterior.curvature_D;delete d.anterior.curvature_type;assert.equal(C.mapGrid(C.validate(d),'anterior','curvature_D'),null);});
test('elevation needs reference metadata',()=>{const d=clone();delete d.anterior.elevation_reference;assert.throws(()=>C.validate(d));});
test('no complete measured cells means no surface',()=>{const d=clone();d.anterior.z_mm=d.anterior.z_mm.map((r,j)=>r.map((_,i)=>i===j?0:null));assert.throws(()=>C.validate(d));});
test('sample extrema use actual arrays',()=>{const d=C.validate(demo);const p=C.extrema(d,'anterior','thickness_um','min');assert.equal(d.thickness_um[p.row][p.col],p.value);assert.equal(d.anterior.z_mm[p.row][p.col],p.z);});
test('per-surface coordinate override blocked',()=>{const d=clone();d.posterior.coordinate_system={origin:'posterior_apex'};assert.throws(()=>C.validate(d));});
test('unexpected unit aliases blocked',()=>{const d=clone();d.units.z_anterior='mm';assert.throws(()=>C.validate(d));});
console.log(count+' surface-contract tests passed.');
