/* Numerical algorithms plus optional private paired-report integration tests. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {createCanvas,loadImage,Image}=require('@napi-rs/canvas');
global.document={createElement:()=>createCanvas(1,1)};global.Image=Image;
const N=require('../components/cornea/numerical_maps.js'),T=require('../components/cornea/map_texture.js'),C=require('../components/cornea/surface_schema.js'),V=require('../components/cornea/visit_comparison.js');
const xs=Array.from({length:81},(_,i)=>(i-40)/10),grid=v=>xs.map(()=>xs.map(()=>v));
const base={kind:'synthetic',source:'synthetic_fixture',x:xs,y:xs,coordinates:{x_positive:'report-right',y_positive:'superior'},count:6561,dp:1,unit:'D',definition:'axial'};
const curvature={...base,role:'curvature_front',values:grid(337.5/7.8)},thickness={...base,role:'thickness',unit:'µm',dp:0,definition:'device_pachymetry',values:grid(500)};
const model=N.reconstruct(curvature,thickness);assert(model);assert.equal(model.kind,'estimated');assert(Math.abs(model.z[40][70]-(Math.sqrt(7.8**2-3**2)-7.8))<.001);assert.equal(model.thickness[40][40],500);console.log('PASS reconstructed constant-radius sphere agrees with analytical sag (<1 µm integration error)');
const thin={...thickness,values:grid(475)},d=N.compare(thickness,thin);assert(d.values.flat().every(v=>v===-25));assert(N.compare(thickness,thickness).values.flat().every(v=>v===0));const moreCurved={...curvature,values:grid(337.5/6.8)},sharper=N.reconstruct(moreCurved,thin);assert(sharper.z[40][70]<model.z[40][70]);assert.equal(sharper.thickness[40][40],475);assert.deepEqual(curvature.values,grid(337.5/7.8));console.log('PASS signed changes, identical-input zero, geometry responds to both curvature and thickness, input maps unmodified');
const missing={...thin,values:structuredClone(thin.values)};missing.values[40][40]=null;assert.equal(N.compare(thickness,missing).values[40][40],null);assert.equal(N.pick(N.compare(thickness,missing),.5,.5).value,null);assert.throws(()=>N.compare(thickness,{...thin,source:'device_numeric_export'}));assert.throws(()=>N.compare(thickness,{...thin,definition:'different'}));assert.throws(()=>N.compare(thickness,{...thin,x:[-3,0,3]}));assert.equal(N.reconstruct({...curvature,definition:'tangential'},thickness),null);console.log('PASS missing data, mixed sources/definitions/coordinates and unsupported geometry inputs guarded');
const raw=JSON.parse(fs.readFileSync(__dirname+'/../components/cornea/synthetic_demo.json'));raw.schema='nkpi-corneal-maps-1';delete raw.anterior.z_mm;delete raw.posterior;raw.comparison={alignment:'verified_common_grid',registration_id:'test-pair',map_definition_id:'test-maps'};const a=C.validate(raw),b=structuredClone(a);b.visit='latest';b.thickness_um=b.thickness_um.map(row=>row.map(v=>v===null?null:v-12));assert.equal(V.compare(a,b,'thickness').limit,12);assert.equal(N.measuredModel(a),null);delete b.comparison;assert.throws(()=>V.compare(a,b,'thickness'));console.log('PASS map-only numerical import and difference without z geometry; registration still required');
async function reports(filename){const JSZip=require('../components/extractor/vendor/jszip-3.10.1.min.js'),zip=await JSZip.loadAsync(fs.readFileSync(filename)),groups=new Map();for(const name of Object.keys(zip.files)){const m=name.match(/^(.*?)\.PdfReport\.0000-00(06|11)\.jpe?g$/i);if(!m)continue;const g=groups.get(m[1])||{};g[m[2]==='06'?'topometric':'belin']=name;groups.set(m[1],g);}assert.equal(groups.size,2);const result=[];for(const group of groups.values()){const maps={};for(const [kind,role]of [['topometric','curvature_front'],['belin','thickness']]){const image=await loadImage(await zip.file(group[kind]).async('nodebuffer')),loaded=T.analyze(image);loaded.regions=T.describe(loaded,kind);const candidate={page:{kind},loaded,region:T.roleRegion(loaded.regions,role)};maps[role]=await N.extract(candidate);assert(maps[role].coverage>.65);assert.equal(maps[role].kind,'estimated');}result.push(maps);}return result;}
(async()=>{const args=process.argv.slice(2);if(args.length){assert.equal(args.length,2);const aa=await reports(args[0]),bb=await reports(args[1]);for(let eye=0;eye<2;eye++){for(const role of ['curvature_front','thickness']){const a=aa[eye][role],b=bb[eye][role],delta=N.compare(a,b);assert(delta.count>2500);assert(delta.values.flat().some(v=>v!==null&&Math.abs(v)>.01));assert(N.compare(a,a).values.flat().filter(Number.isFinite).every(v=>v===0));console.log('PASS paired eye',eye+1,role,'baseline/latest samples',a.count,b.count,'overlap',delta.count,'limit',delta.limit);if(process.env.NKPI_PREVIEW_DIR)fs.writeFileSync(process.env.NKPI_PREVIEW_DIR+'/change-'+eye+'-'+role+'.png',N.texture(delta).toBuffer('image/png'));}const am=N.reconstruct(aa[eye].curvature_front,aa[eye].thickness),bm=N.reconstruct(bb[eye].curvature_front,bb[eye].thickness);assert(am?.count>3000&&bm?.count>3000);assert.notDeepEqual(am.z,bm.z);assert.notDeepEqual(am.thickness,bm.thickness);}
const c=aa[0].thickness.candidate,im=c.loaded.image,copy=createCanvas(im.width,im.height),ctx=copy.getContext('2d');ctx.drawImage(im,0,0);ctx.fillStyle='#fff';ctx.fillRect(1148,140,8,8);await assert.rejects(()=>N.extract({...c,loaded:{...c.loaded,image:copy}}),/calibration|printed scale/);const blank=createCanvas(im.width,im.height);blank.getContext('2d').drawImage(im,0,0);blank.getContext('2d').fillStyle='#eee';blank.getContext('2d').fillRect(765,125,12,255);const top=aa[0].curvature_front.candidate;await assert.rejects(()=>N.extract({...top,loaded:{...top.loaded,image:blank}}),/frame|calibration/);console.log('PASS changed legend and unsupported frame rejected; no numeric fallback');}
console.log('ALL NUMERICAL MAP TESTS PASSED');})().catch(e=>{console.error(e);process.exitCode=1;});
