/* Repair layer: broader format discovery + explicit source-page association.
 * Does not change OCR math, model features, source verification or 3D geometry.
 */
'use strict';
let importRepairPending=null,importRepairDiagnostics=[],forceManualImport=false;
const IMPORT_HELP={
 'pdf-library-unavailable':'PDF renderer could not load. This network must allow the pinned PDF.js module and worker, or the source can be exported as JPEG/PNG.',
 'pdf-render-failed':'A PDF could not be rendered. It may be encrypted, damaged or unsupported.',
 'tiff-library-unavailable':'TIFF decoder could not load. Allow its pinned assets or export JPEG/PNG/PDF.',
 'tiff-orientation':'A TIFF has a nonstandard orientation; convert to a correctly oriented report image before review.',
 'dicom-transfer-syntax':'A DICOM uses unsupported compression (such as JPEG 2000, JPEG-LS or RLE). Export its report pages as JPEG/PNG/PDF. Renaming it will not convert it.',
 'dicom-pixel-format':'A DICOM contains unsupported diagnostic/OCT pixels rather than a supported report image.',
 'dicom-raw':'A file labelled DICOM has no recognized Part 10 header. Its transfer syntax was not guessed.',
 'bigtiff':'BigTIFF is detected but not supported by this adapter.',
 'dicom-no-pixels':'A DICOM has no displayable report pixels or encapsulated PDF.',
 'image-decode-failed':'An image could not be decoded by this browser.',
 'broken-image':'An image filename does not contain recognized image bytes.',
 'broken-pdf':'A file named PDF does not contain a valid PDF header.',
 'broken-zip':'An entry named ZIP is not a readable nested archive.'
};
function repairNode(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls+(cls==='primary'?' primary-button':cls==='secondary'?' secondary-button':'');if(text!==undefined)e.textContent=text;return e;}
function repairSection(){let box=el('archiveDiagnostics');if(!box){box=repairNode('details','archive-diagnostics');box.id='archiveDiagnostics';el('processButton').closest('section').append(box);}return box;}
function updateImportDiagnostic(label,diagnostic){const index=importRepairDiagnostics.findIndex(d=>d.slot===label),r={slot:label,...diagnostic};if(index<0)importRepairDiagnostics.push(r);else importRepairDiagnostics[index]=r;const box=repairSection(),wasOpen=box.open;box.replaceChildren();box.append(repairNode('summary','',`Report-file detection · ${importRepairDiagnostics.reduce((s,d)=>s+d.pages,0)} readable pages`));for(const d of importRepairDiagnostics){box.append(repairNode('p','',d.slot+': '+NKPIArchiveReader.summarize(d)));for(const [key,n] of Object.entries(d.issues))box.append(repairNode('p','import-issue',`${n} item(s): ${IMPORT_HELP[key]||key.replaceAll('-',' ')+' — source format needs review.'}`));}box.append(repairNode('p','muted','Counts only. The diagnostic download excludes names, filenames, dates, image pixels and measurements.'));
 const b=repairNode('button','secondary','Download file-type diagnostic');b.type='button';b.onclick=()=>{const clean=importRepairDiagnostics.map(d=>({slot:d.slot,...NKPIArchiveReader.safeDiagnostics(d)}));const u=URL.createObjectURL(new Blob([JSON.stringify({release:'5.0.0-numerical-maps',imports:clean},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='NKPI_import_file_types.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);};box.append(b);box.open=wasOpen||importRepairDiagnostics.some(d=>Object.keys(d.issues).length||d.pages===0);syncFrameHeight();}
function repairCancel(){if(importRepairPending){importRepairPending.reject(new NKPIArchiveReader.ImportError('cancelled','Report selection cancelled.'));importRepairPending=null;}el('sourcePageRepair')?.remove();}
const repairReset=resetResultsOnly;
resetResultsOnly=function(){repairCancel();importRepairDiagnostics=[];el('archiveDiagnostics')?.remove();return repairReset();};
// Retain folder/container scope. Equal timestamps from different directories may
// refer to different eyes or repeat scans and must never merge into one study.
reportFilenameParts=function(filename){const path=String(filename).replace(/\\/g,'/'),name=basename(path),m=name.match(/^(.+?)\.PdfReport\.0000(-\d{4})?\.(jpe?g|png|webp|bmp)$/i);if(!m)return null;return {prefix:path.slice(0,path.lastIndexOf('/')+1)+m[1],suffix:m[2]||'-0001'};};
isSupportedReportImage=function(filename){return /\.(jpe?g|png|webp|bmp)$/i.test(String(filename).trim());};
function imageSourceName(loaded,filename){return loaded.metadata[filename]?.original||filename;}
function makeDescriptors(loaded,label){const groups=new Map(),unassigned=[];for(const f of loaded.imageFiles){const p=reportFilenameParts(f);if(!p||loaded.metadata[f]?.converted){unassigned.push(f);continue;}if(!groups.has(p.prefix))groups.set(p.prefix,new Map());const group=groups.get(p.prefix);if(group.has(p.suffix))return null;group.set(p.suffix,f);}if(unassigned.length||!groups.size)return null;const descriptors=[];for(const [prefix,pages] of groups){if(!pages.has(REQUIRED_SUFFIXES.topometric)||!pages.has(REQUIRED_SUFFIXES.belin))return null;const chosen={topometric:pages.get(REQUIRED_SUFFIXES.topometric),belin:pages.get(REQUIRED_SUFFIXES.belin),progression:pages.get(REQUIRED_SUFFIXES.progression)||null};descriptors.push({visitLabel:label,zip:loaded.zip,prefix,timestamp:timestampFromPrefix(prefix),viewerPages:[...pages].sort(([a],[b])=>a.localeCompare(b)).map(([,f])=>f),pages:chosen,originalPages:Object.fromEntries(Object.entries(chosen).filter(([,f])=>f).map(([k,f])=>[k,imageSourceName(loaded,f)]))});}return descriptors;}
function verifiedAssociations(rows,loaded,label){const taken=new Map(),descriptors=[];for(const [i,r] of rows.entries()){if(!['OD','OS'].includes(r.eye))throw new Error(`Study ${i+1}: choose the eye printed on the reports.`);if(!r.topometric||!r.belin)throw new Error(`Study ${i+1}: select the KC-Staging and Belin/Ambrósio source pages.`);if(r.topometric===r.belin&&!r.manual)throw new Error(`Study ${i+1}: automatic extraction needs the two report pages separately. For a combined page, select manual entry.`);
 const associated=[...new Set([r.topometric,r.belin,r.progression,...(r.extras||[])].filter(Boolean))];for(const f of associated){if(!loaded.imageFiles.includes(f))throw new Error('A selected page is no longer available.');if(taken.has(f))throw new Error('The same report page was assigned to more than one study. Match each eye and repeat scan separately.');taken.set(f,i);}
 let timestamp=null;if(r.datetime){timestamp=new Date(r.datetime);if(!Number.isFinite(timestamp.getTime()))throw new Error('Check the local examination date/time.');}
 const pages={topometric:r.topometric,belin:r.belin,progression:r.progression||null};descriptors.push({visitLabel:label,zip:loaded.zip,prefix:`operator-study-${i+1}`,forcedEye:r.eye,timestamp,sourceFormat:'operator-associated-report-pages',pageResolution:'Operator-confirmed report titles, eye and examination',viewerPages:associated,pages,originalPages:Object.fromEntries(Object.entries(pages).filter(([,f])=>f).map(([k,f])=>[k,imageSourceName(loaded,f)])),manual:r.manual});}
 if(!descriptors.length)throw new Error('Add at least one source study.');return descriptors;}
// v4.5: automatically identify decoded DICOM/PDF/TIFF report pages.
function autoHeaderEye(text){const t=(" "+String(text||"").toUpperCase().replace(/[^A-Z0-9]+/g," ")+" ");const od=/\bOD\b/.test(t),os=/\bOS\b/.test(t);return od&&!os?"OD":os&&!od?"OS":null;}
async function autoIdentifyConvertedReports(loaded,label,epoch,workers){const records=[];for(let i=0;i<loaded.imageFiles.length;i++){if(epoch!==state.processEpoch)throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');const f=loaded.imageFiles[i];setProgress(18+(i/Math.max(1,loaded.imageFiles.length))*22,`Identifying ${label} report ${i+1} of ${loaded.imageFiles.length}…`,'Reading report titles and printed eye automatically. No page selection is required.');try{const blob=await loaded.zip.file(f).async('blob');const bitmap=await blobToBitmap(blob);const result=await recognizeHeader(workers[i%workers.length],bitmap);bitmap.close?.();const pageType=classifyReportTitle(result.text);if(pageType)records.push({filename:f,index:i,pageType,eye:autoHeaderEye(result.text),title:result.text});}catch(_){}}
 const descriptors=[];for(const eye of ['OD','OS']){const tops=records.filter(r=>r.pageType==='topometric'&&r.eye===eye),belins=records.filter(r=>r.pageType==='belin'&&r.eye===eye),progs=records.filter(r=>r.pageType==='progression'&&r.eye===eye),usedB=new Set(),usedP=new Set();for(const top of tops){const b=belins.filter(r=>!usedB.has(r.filename)).sort((a,b2)=>Math.abs(a.index-top.index)-Math.abs(b2.index-top.index))[0];if(!b)continue;usedB.add(b.filename);const pr=progs.filter(r=>!usedP.has(r.filename)).sort((a,b2)=>Math.abs(a.index-b.index)-Math.abs(b2.index-b.index))[0]||null;if(pr)usedP.add(pr.filename);const associated=[top.filename,b.filename,pr?.filename].filter(Boolean);descriptors.push({visitLabel:label,zip:loaded.zip,prefix:`auto-${eye}-${top.index}`,forcedEye:eye,timestamp:null,sourceFormat:'automatic-decoded-report',pageResolution:'Automatic title + printed-eye OCR',viewerPages:associated,pages:{topometric:top.filename,belin:b.filename,progression:pr?.filename||null},originalPages:Object.fromEntries([['topometric',top.filename],['belin',b.filename],['progression',pr?.filename||null]].filter(([,f])=>f).map(([k,f])=>[k,imageSourceName(loaded,f)]))});}}
 if(!descriptors.length){const pairs=pairGenericPages(records);if(pairs.length>0&&pairs.length<=2){for(const [i,pair] of pairs.entries())descriptors.push({visitLabel:label,zip:loaded.zip,prefix:`auto-title-${i}`,timestamp:null,sourceFormat:'automatic-decoded-report',pageResolution:'Automatic report-title OCR; laterality verified during extraction',viewerPages:[pair.topometric,pair.belin,pair.progression].filter(Boolean),pages:{topometric:pair.topometric,belin:pair.belin,progression:pair.progression||null},originalPages:Object.fromEntries([['topometric',pair.topometric],['belin',pair.belin],['progression',pair.progression||null]].filter(([,f])=>f).map(([k,f])=>[k,imageSourceName(loaded,f)]))});}}
 return descriptors;}

async function chooseReportPages(loaded,label,epoch){repairCancel();hideProgress();const box=repairNode('section','card source-page-repair');box.id='sourcePageRepair';el('detectedSection').before(box);box.append(repairNode('h2','',`${label}: report pages found`),repairNode('p','',`Found ${loaded.imageFiles.length} readable page(s). Match the report titles, eye and examination below. No file renaming or second upload is required.`),repairNode('p','muted','An unfamiliar layout is not proof that measurements are missing. The software does not pair unrelated pages by their order. Exclude OCT images, other patients and unrelated visits.'));
 const columns=repairNode('div','repair-columns'),left=repairNode('div','repair-preview'),right=repairNode('div','repair-associations');columns.append(left,right);box.append(columns);
 const previewSelect=repairNode('select',''),preview=repairNode('img','repair-report');preview.alt='Selected original/decoded source report; verify printed eye and title';const caption=repairNode('p','muted');left.append(repairNode('label','', 'Preview source report'),previewSelect,preview,caption);
 const labels=new Map(loaded.imageFiles.map((f,i)=>[f,`Page ${String(i+1).padStart(3,'0')} · ${loaded.metadata[f]?.format||'image'}${loaded.metadata[f]?.converted?' · document/frame '+loaded.metadata[f].page:''}`]));
 for(const [value,text] of labels){const op=repairNode('option','',text);op.value=value;previewSelect.append(op);}
 const urls=new Map();async function show(f){if(!f)return;const file=loaded.zip.file(f);if(!file)return;const b=await file.async('blob');if(epoch!==state.processEpoch)return;if(!urls.has(f))urls.set(f,registerPreviewUrl(b));preview.src=urls.get(f);previewSelect.value=f;caption.textContent=labels.get(f)+' · the full report is retained; do not assign it based on color alone.';syncFrameHeight();}
 previewSelect.onchange=()=>show(previewSelect.value);await show(loaded.imageFiles[0]);
 const cards=[],confirm=repairNode('input',''),confirmation=repairNode('label','repair-confirm');confirm.type='checkbox';confirmation.append(confirm,repairNode('span','','I matched the printed titles and confirmed that each study contains one patient, one eye and one examination.'));
 const status=repairNode('div','alert error');status.hidden=true;
 function select(label,optional=false,multiple=false){const wrap=repairNode('label','field'),s=repairNode('select','');if(multiple){s.multiple=true;s.size=4;}else{const blank=repairNode('option','',optional?'Not included':'Choose page…');blank.value='';s.append(blank);}for(const [value,text] of labels){const op=repairNode('option','',text);op.value=value;s.append(op);}wrap.append(repairNode('span','',label),s);s.onchange=()=>{confirm.checked=false;show(multiple?s.selectedOptions[0]?.value:s.value);};return {wrap,s};}
 function add(){if(cards.length>=8)return;confirm.checked=false;const card=repairNode('div','repair-study'),title=repairNode('h3','',`Source study ${cards.length+1}`),eye=repairNode('select','');for(const [v,t] of [['','Choose eye…'],['OD','Right eye — OD'],['OS','Left eye — OS']]){const o=repairNode('option','',t);o.value=v;eye.append(o);}const ew=repairNode('label','field');ew.append(repairNode('span','','Printed eye'),eye);eye.onchange=()=>{confirm.checked=false;};const top=select('Topometric / KC-Staging page'),belin=select('Belin/Ambrósio Enhanced Ectasia page'),prog=select('ABCD Progression page (optional)',true),extra=select('Additional map pages from this same study (optional)',true,true),dt=repairNode('input','');dt.type='datetime-local';dt.onchange=()=>{confirm.checked=false;};const dw=repairNode('label','field');dw.append(repairNode('span','','Examination date/time (optional; browser only)'),dt);const manual=repairNode('input','');manual.type='checkbox';manual.onchange=()=>{confirm.checked=false;};const mw=repairNode('label','repair-confirm');mw.append(manual,repairNode('span','','Enter measurements manually from these pages (skip OCR)'));
 const details=repairNode('details','');details.append(repairNode('summary','','Extra maps, examination date and manual-entry option'),extra.wrap,dw,mw);const remove=repairNode('button','secondary','Remove study');remove.type='button';const record={card,eye,top:top.s,belin:belin.s,prog:prog.s,extra:extra.s,dt,manual};remove.onclick=()=>{cards.splice(cards.indexOf(record),1);card.remove();confirm.checked=false;syncFrameHeight();};card.append(title,ew,top.wrap,belin.wrap,prog.wrap,details,remove);cards.push(record);right.append(card);syncFrameHeight();}
 add();const addButton=repairNode('button','secondary','Add other eye / repeat study');addButton.type='button';addButton.onclick=add;right.append(addButton);box.append(confirmation,status);const actions=repairNode('div','repair-actions'),next=repairNode('button','primary','Use these pages → verify measurements'),cancel=repairNode('button','secondary','Cancel import');next.type=cancel.type='button';actions.append(next,cancel);box.append(actions);box.scrollIntoView({behavior:'smooth',block:'start'});syncFrameHeight();
 if(epoch!==state.processEpoch){box.remove();throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');}
 return await new Promise((resolve,reject)=>{importRepairPending={reject};cancel.onclick=()=>{resetResultsOnly();invalidateVerifiedPayload();};next.onclick=()=>{try{if(epoch!==state.processEpoch)throw new Error('Selected source changed. Import again.');if(!confirm.checked)throw new Error('Confirm the source-page association before continuing.');const rows=cards.map(c=>({eye:c.eye.value,topometric:c.top.value,belin:c.belin.value,progression:c.prog.value,extras:[...c.extra.selectedOptions].map(o=>o.value),datetime:c.dt.value,manual:c.manual.checked}));const result=verifiedAssociations(rows,loaded,label);importRepairPending=null;box.remove();resolve(result);}catch(e){status.textContent=e.message;status.hidden=false;syncFrameHeight();}};});}
async function blankSourceStudy(d,message){const epoch=state.processEpoch,sourcePages={};for(const [kind,f] of Object.entries(d.pages)){if(f){const blob=await d.zip.file(f).async('blob');if(epoch!==state.processEpoch)throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');sourcePages[kind]=registerPreviewUrl(blob);}}const values=Object.fromEntries(NKPIImport.FIELDS.map(k=>[k,null]));const study={eye:d.forcedEye||null,prefix:d.prefix,timestamp:d.timestamp||null,sourcePages,values,complete:false,audit:Object.fromEntries(NKPIImport.FIELDS.map(k=>[k,{quality:'Unavailable',autoConfirmed:false,reason:message}])),manualEdits:{},extractionWarning:message,eyeResolution:d.forcedEye?'Explicit source-page assignment':'Confirm printed eye before entry'};return await attachAssociatedReportPages(d,study);}
parseArchive=async function(file,label){const epoch=state.processEpoch;let loaded;try{loaded=await NKPIArchiveReader.open(file,{cancelled:()=>epoch!==state.processEpoch,onDiagnostic:d=>{if(epoch===state.processEpoch)updateImportDiagnostic(label,d);}});}catch(e){if(e.code==='cancelled')throw e;throw new Error(`${label}: ${e.message||'Report archive could not be opened.'}`);}if(epoch!==state.processEpoch)throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');if(!loaded.imageFiles.length){const issues=Object.keys(loaded.diagnostic.issues),detail=issues.map(k=>IMPORT_HELP[k]).filter(Boolean).join(' ');throw new Error(`${label}: ${NKPIArchiveReader.summarize(loaded.diagnostic)} ${detail||'This export does not contain a supported displayable report. Open Report-file detection below to see the formats found. The software has not determined that the six measurements are absent.'}`);}
 let descriptors=forceManualImport?null:makeDescriptors(loaded,label);
 let workers=null;
 if(!descriptors && !forceManualImport){try{workers=await ensureWorkers();descriptors=await autoIdentifyConvertedReports(loaded,label,epoch,workers);}catch(_){descriptors=null;}}
 if(!descriptors || !descriptors.length)descriptors=await chooseReportPages(loaded,label,epoch);
 try{if(!workers && descriptors.some(d=>!d.manual))workers=await ensureWorkers();}catch(_){/* Source pages remain available; blank verified entry is the safe fallback. */}
 const results=[];for(let i=0;i<descriptors.length;i++){if(epoch!==state.processEpoch)throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');const d=descriptors[i];setProgress(25+65*i/descriptors.length,`Reading source study ${i+1} of ${descriptors.length}…`,'Report images stay in this browser. Every value must be verified.');let study;
  if(d.manual||!workers){study=await blankSourceStudy(d,d.manual?'Manual source entry selected. Enter and verify all six measurements.':'Automatic extraction was unavailable. The source pages are loaded; enter and verify all six measurements.');}
  else try{study=await extractStudy(d,workers[i%workers.length]);}catch(_){if(epoch!==state.processEpoch)throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');study=await blankSourceStudy(d,'Automatic extraction did not complete. The report remains available; enter and verify all six measurements.');}
  if(d.forcedEye){study.eye=d.forcedEye;study.eyeResolution='Operator-confirmed source-page association';}if(epoch!==state.processEpoch)throw new NKPIArchiveReader.ImportError('cancelled','Source changed.');results.push(study);
 }return reconcileStudyLaterality(results);
};
const repairVisitCard=visitCard;
visitCard=function(study,...args){const card=repairVisitCard(study,...args);if(study.extractionWarning)card.prepend(repairNode('p','alert warning',study.extractionWarning));return card;};
document.addEventListener('DOMContentLoaded',()=>{const b=repairNode('button','secondary','Choose report pages manually');b.id='manualPageSelection';b.type='button';b.onclick=async()=>{if(state.processing)return;forceManualImport=true;try{await processFiles();}finally{forceManualImport=false;}};el('processButton').after(b);for(const id of ['baselineZip','earlierZip','laterZip'])el(id)?.setAttribute('accept','.zip,.pdf,.dcm,.dicom,.tif,.tiff,.jpg,.jpeg,.jfif,.png,.bmp,.webp');const help=repairNode('p','muted','ZIP, PDF or supported report images. Nested ZIPs and supported DICOM/TIFF reports are read locally. Unfamiliar page layouts can be matched without another upload.');b.after(help);});
