/* Optional, same-ZIP numerical discovery. Explicit report-file association only.
 * Supports the documented NKPI JSON surface contract, NOT proprietary binaries.
 * No image pixels, summary indices or units are reverse-engineered into geometry.
 */
'use strict';
const surfaceIndexJobs=new WeakMap();
function safeZipPath(p){return typeof p==='string'&&p.length>0&&p.length<1024&&!p.startsWith('/')&&!p.includes('\\')&&!p.split('/').includes('..')&&!p.includes('\0')&&!/^[a-z]+:/i.test(p);}
async function readSurfaceJSON(zip,path,limit=12*1024*1024){if(!safeZipPath(path))throw new Error('Invalid local archive path.');const entry=zip.file(path);if(!entry||entry.dir)throw new Error('Numerical file missing from ZIP.');if((entry._data?.uncompressedSize||0)>limit)throw new Error('Numerical file exceeds size limit.');const text=await entry.async('string');if(text.length>limit)throw new Error('Numerical file exceeds size limit.');return JSON.parse(text);}
async function surfaceIndex(zip){if(surfaceIndexJobs.has(zip))return surfaceIndexJobs.get(zip);const job=(async()=>{if(!zip.file('nkpi-surface-index.json'))return null;const raw=await readSurfaceJSON(zip,'nkpi-surface-index.json',100000);if(!raw||raw.schema!=='nkpi-surface-index-1'||!Array.isArray(raw.entries)||raw.entries.length>32||Object.keys(raw).some(k=>!['schema','entries'].includes(k)))throw new Error('Unsupported numerical index.');for(const e of raw.entries){if(!e||Object.keys(e).some(k=>!['report','surface'].includes(k))||!safeZipPath(e.report)||!safeZipPath(e.surface)||!e.surface.toLowerCase().endsWith('.json'))throw new Error('Invalid numerical index association.');}return raw.entries;})();surfaceIndexJobs.set(zip,job);return job;}
async function linkedNumericalSurface(descriptor,study){const zip=descriptor.zip;if(!zip||typeof zip.file!=='function')return null;try{const index=await surfaceIndex(zip),associated=[...Object.values(descriptor.pages),...Object.values(descriptor.originalPages||{})].filter(Boolean),paths=[];if(index){for(const e of index)if(associated.includes(e.report))paths.push(e.surface);}if(descriptor.prefix&&safeZipPath(descriptor.prefix+'.surface.json')&&zip.file(descriptor.prefix+'.surface.json'))paths.push(descriptor.prefix+'.surface.json');const unique=[...new Set(paths)];if(!unique.length)return null;if(unique.length!==1)throw new Error('More than one numerical surface matches this report; no geometry was selected.');const raw=await readSurfaceJSON(zip,unique[0]);const surface=CornealData.validate(raw);if(surface.eye!==study.eye)throw new Error('Numerical surface eye does not match the selected report.');return {data:surface,notice:'Supported numerical surface found in the same ZIP, explicitly linked to the selected report.'};}catch(_){return {data:null,notice:'A linked numerical file was present but could not pass association or structural checks. Reference geometry is shown instead.'};}}
const originalAttachMaps=attachAssociatedReportPages;
attachAssociatedReportPages=async function(descriptor,study,generation=reportGeneration,worker=null){const result=await originalAttachMaps(descriptor,study,generation,worker);if(generation!==reportGeneration)return result;const numerical=await linkedNumericalSurface(descriptor,result);if(generation!==reportGeneration)return result;if(numerical)result.numericalSurface=numerical;return result;};
