/* Shared, numeric-only interface contract. No names, filenames, DOB or report pixels. */
(function(root){'use strict';
const F=[
{key:'A',label:'A · ARC',name:'Anterior radius',unit:'mm',decimals:2,low:2.5,high:12.5},
{key:'B',label:'B · PRC',name:'Posterior radius',unit:'mm',decimals:2,low:2.5,high:12.5},
{key:'C',label:'C · Thinnest',name:'Minimum pachymetry',unit:'µm',decimals:0,low:200,high:800},
{key:'Kmax',label:'Kmax',name:'Maximum keratometry',unit:'D',decimals:1,low:20,high:100},
{key:'BAD_D',label:'BAD-D',name:'Belin–Ambrósio deviation',unit:'',decimals:2,low:-5,high:60},
{key:'ARTmax',label:'ARTmax',name:'Relational thickness',unit:'',decimals:1,low:1,high:1000}];
const finite=v=>typeof v!=='boolean'&&v!==null&&v!==undefined&&['string','number'].includes(typeof v)&&String(v).trim()!==''&&Number.isFinite(Number(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function blank(eye){return {eye,enabled:eye==='OD',mode:'baseline',age:'',first:{},latest:{},interval_days:'',scan_quality:{first:'unknown',latest:'unknown'},treatment:'unknown',verified:false,landmarks:{},context:{},demo:false};}
function imported(p){const clean=root.NKPIImport.sanitize(p),paired=clean.mode==='longitudinal',scans=paired?clean.baseline:clean.eyes;return Object.keys(scans).map(eye=>{const meta=clean.display_by_eye?.[eye]||{};return {...blank(eye),enabled:true,mode:clean.mode,age:clean.age,first:scans[eye],latest:paired?clean.followup[eye]:{},interval_days:paired?clean.interval_days_by_eye[eye]:'',scan_quality:{first:meta.first_quality||'unknown',latest:meta.latest_quality||'unknown'},landmarks:meta.landmarks||{},verified:true};});}
function payload(c){return {eye:c.eye,mode:c.mode,age:c.age,first:Object.fromEntries(F.map(f=>[f.key,c.first[f.key]??''])),latest:c.mode==='longitudinal'?Object.fromEntries(F.map(f=>[f.key,c.latest[f.key]??''])):null,interval_days:c.mode==='longitudinal'?c.interval_days:null,scan_quality:c.scan_quality,treatment:c.treatment,verified:c.verified,landmarks:c.landmarks,context:c.context,demo:c.demo};}
const api={features:F,finite,esc,blank,imported,payload};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.NKPI=api;
})(typeof window!=='undefined'?window:globalThis);

/* Independently verify model rows/explanations against the current submitted snapshot. */
(function(root){'use strict';
const S = typeof module!=='undefined'&&module.exports ? module.exports : root.NKPI;
function stable(o){if(Array.isArray(o))return '['+o.map(stable).join(',')+']';if(o&&typeof o==='object')return '{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+stable(o[k])).join(',')+'}';return JSON.stringify(o);}
const numeric = v=>S.finite(v)?Number(v):null;
function canonical(c){const paired=c.mode==='longitudinal',values=v=>Object.fromEntries(S.features.map(f=>[f.key,numeric(v?.[f.key])])),q=c.scan_quality||{},quality=v=>['ok','warning','unknown'].includes(q[v])?q[v]:'unknown';let coords=null;const keys=['thin_x','thin_y','kmax_x','kmax_y'];if(c.landmarks?.verified===true&&keys.every(k=>S.finite(c.landmarks[k])&&Math.abs(Number(c.landmarks[k]))<=6))coords=Object.fromEntries(keys.map(k=>[k,Number(c.landmarks[k])]));return {eye:c.eye,mode:c.mode,age:numeric(c.age),first:values(c.first),latest:paired?values(c.latest):null,interval_days:paired&&S.finite(c.interval_days)&&Number(c.interval_days)>=1&&Number(c.interval_days)<=36525&&Number.isInteger(Number(c.interval_days))?Number(c.interval_days):null,scan_quality:Object.fromEntries((paired?['first','latest']:['first']).map(v=>[v,quality(v)])),verified:c.verified===true,treatment:['untreated','treated','unknown'].includes(c.treatment)?c.treatment:'unknown',context:Object.fromEntries(['lenses','rubbing','vision'].map(k=>[k,c.context?.[k]===true])),demo:c.demo===true,landmarks:coords};}
function expectedFeatures(c,specs){return Object.fromEntries(Object.entries(specs).map(([name,s])=>{let v;if(s.source==='age')v=c.age;else if(s.source==='interval_years')v=c.interval_days/(s.days_per_year||365.2425);else if(s.source==='change')v=c.latest[s.key]-c.first[s.key];else if(['first','latest'].includes(s.source))v=c[s.source][s.key];else throw new Error('Unknown feature mapping');return [name,v*(s.direction??1)];}));}
function verify(c,r,config){if(!r||r.eye!==c.eye||r.case?.eye!==c.eye)throw new Error('Eye/result mismatch');if(stable(canonical(c))!==stable(r.case))throw new Error('Input/result snapshot mismatch');if(r.model_sha256!==config.models[c.mode].sha256)throw new Error('Unexpected model version');if(!r.prediction){if(r.status!=='held')throw new Error('Missing score status');return true;}if(r.status!=='ready'||!Number.isFinite(r.prediction.nkpi)||r.prediction.nkpi<0||r.prediction.nkpi>100)throw new Error('Invalid score');const expected=expectedFeatures(r.case,config.feature_specs[c.mode]),effects=r.prediction.effects;if(!Array.isArray(effects)||effects.length!==Object.keys(expected).length||new Set(effects.map(e=>e.feature)).size!==effects.length)throw new Error('Incomplete explanation');for(const e of effects){if(!(e.feature in expected)||!Number.isFinite(e.value)||Math.abs(e.value-expected[e.feature])>1e-9)throw new Error('Input/explanation mismatch: '+e.feature);const ref=config.references[c.mode][e.feature];if(!ref||!Number.isFinite(e.reference)||Math.abs(e.reference-ref.median)>1e-10||!Number.isFinite(e.effect))throw new Error('Training median/effect mismatch: '+e.feature);}const impact=r.impact_audit;if(impact?.cohort?.eyes!==config.models[c.mode].n_eyes||impact?.cohort?.patients!==config.models[c.mode].n_patients)throw new Error('Training cohort metadata mismatch');if(!impact||!Array.isArray(impact.rows)||impact.rows.length!==effects.length||new Set(impact.rows.map(a=>a.feature)).size!==effects.length)throw new Error('Incomplete ranked impact audit');for(const a of impact.rows){const e=effects.find(e=>e.feature===a.feature),spec=config.feature_specs[c.mode][a.feature];if(!spec||a.source!==spec.source||a.key!==spec.key||a.direction!==(spec.direction??1))throw new Error('Ranked feature mapping mismatch');if(!e||!Number.isFinite(a.difference_from_median)||Math.abs(a.difference_from_median-(a.value-a.reference))>1e-9||!Number.isFinite(a.value)||!Number.isFinite(a.reference)||!Number.isFinite(a.effect_points)||!Number.isFinite(a.nkpi_at_median)||Math.abs(a.value-e.value)>1e-9||Math.abs(a.reference-e.reference)>1e-10||Math.abs(a.effect_points-e.effect)>1e-9||Math.abs(a.nkpi_at_median-(r.prediction.nkpi-e.effect))>1e-9)throw new Error('Ranked impact/result mismatch');}return true;}
Object.assign(S,{stable,canonical,expectedFeatures,verify});
})(typeof window!=='undefined'?window:globalThis);
